version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: PusherServer
    versions:
    - 4.2.0
    - 4.3.1
    - 4.3.2
    - 4.4.0
    - 4.5.0
    - 4.6.0
